### ISSUE TITLE
"Missing required parameter 'email',

### ISSUE THREAD

**Issue by rukshalaw** [smoak/postmark-spamcheck#1]
I am using this library and getting an error while I am passing my email body into the methods. 
The error says "Missing required parameter 'email', but both the methods, GetReport() and GetScore() accepts only one parameter, the email body.

**Comment by smoak** [comment]
Thanks. I'll have a look to see what's going on.

**Comment by smoak** [comment]
It looks like the issue was that I was making the json payload by hand. This caused issues if there were characters that needed to be escaped (e.g. `"`). This has been fixed by using `DataContractJsonSerializer`. Additionally, I have submitted the package to nuget.org to make it easier to use as a dependency.

https://www.nuget.org/packages/PostmarkSpamcheck/

**Comment by rukshalaw** [comment]
Thanks for the update.  When I tried installing the Nuget package this error was thrown.
Could not install package 'PostmarkSpamcheck 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by smoak** [comment]
Yeah, this library only targets `netstandard2.0`. I don't have a windows machine to target net45. How were you using it before?

**Comment by rukshalaw** [comment]
I added the DLL to the project
